### ISSUE TITLE
Allow YAML configuration of the name of the editor

### ISSUE THREAD

**Issue by michalkleiner** [arillo/silverstripe-xhtmleditor-config#1]
The default editor is usually `cms`, but on CWP, it's called `cwp`, so it'd be good to default to `cms` while adding something like `editorname` config option (or similar).

**Comment by banglashi** [comment]
Hi @michalkleiner, valid point. I updated the module to 0.0.2 so you can specify an ```identifier``` for the editor. I used the term identifier because this is how it is referred to in the HtmlEditorConfig.
